version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - static:/static

    depends_on:
      - db

  nginx:
    build:
      context: ./infra/
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - static:/app/staticfiles/
      - media:/app/media/
    depends_on:
      - backend