# Generated by Django 3.2.16 on 2024-02-26 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(200)])),
                ('color', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(code='invalid_color_format', message='Enter a valid color in HEX format.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug_format', message='Enter a valid slug in the format.', regex='^[-a-zA-Z0-9_]+$')])),
            ],
        ),
    ]
