# Generated by Django 3.2.16 on 2024-02-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_tagrecipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
    ]
