name: Backend Testing and Deployment

on:
  push:
    branches:
      - main
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip         
        pip install -r ./backend/requirements.txt

    - name: Load environment variables
      run: |
        set -a
        source /Users/7on/Dev/foodgram-project-react/.env
        set +a

    - name: Test with flake8 and django tests
      run: |
        python -m flake8 backend/
        cd backend/
        python manage.py test

